// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using motionMuseApi.Models;

#nullable disable

namespace motionMuseApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251217164619_AddStravaLinks")]
    partial class AddStravaLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("motionMuseApi.Entities.StravaLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.ToTable("strava_links", (string)null);
                });

            modelBuilder.Entity("motionMuseApi.Models.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ElevationGainInM")
                        .HasColumnType("double precision");

                    b.Property<double>("IntervalDurationInSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("IntervalRestDurationInSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("double precision");

                    b.Property<double>("NumberOfIntervals")
                        .HasColumnType("double precision");

                    b.Property<double>("NumberOfReps")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("trainings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
