export const ON_PREMISE_ATHLETE = {
  id: 17464740,
  username: 'maewen_pelletier',
  resource_state: 3,
  firstname: 'Maewen',
  lastname: 'Pelletier',
  bio: 'Mountain pack - [Trail Running 🏃 | Climbing 🧗‍♂️| Alpinism 🗻 | Skiing 🎿]',
  city: 'Annecy',
  state: '',
  country: '',
  sex: 'M',
  premium: true,
  summit: true,
  created_at: '2016-09-10T20:17:37Z',
  updated_at: '2025-03-16T09:49:02Z',
  badge_type_id: 1,
  weight: 58.0,
  profile_medium:
    'https://dgalywyr863hv.cloudfront.net/pictures/athletes/17464740/25892616/3/medium.jpg',
  profile:
    'https://dgalywyr863hv.cloudfront.net/pictures/athletes/17464740/25892616/3/large.jpg',
  friend: null,
  follower: null,
  blocked: false,
  can_follow: true,
  follower_count: 63,
  friend_count: 53,
  mutual_friend_count: 0,
  athlete_type: 1,
  date_preference: '%m/%d/%Y',
  measurement_preference: 'meters',
  clubs: [
    {
      id: 231407,
      resource_state: 2,
      name: 'The Strava Club',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/231407/5319085/1/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/231407/5319085/1/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/231407/5098428/21/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/231407/5098428/21/small.jpg',
      activity_types: [],
      activity_types_icon: 'sports_multi_normal',
      dimensions: ['moving_time', 'num_activities', 'distance', 'elev_gain'],
      sport_type: 'other',
      localized_sport_type: 'Multisport',
      city: 'San Francisco',
      state: 'California',
      country: 'United States',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'strava',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 107127,
      resource_state: 2,
      name: 'ODLO',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/107127/1901800/6/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/107127/1901800/6/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/107127/13712125/38/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/107127/13712125/38/small.jpg',
      activity_types: [],
      activity_types_icon: 'sports_multi_normal',
      dimensions: ['moving_time', 'num_activities', 'distance', 'elev_gain'],
      sport_type: 'other',
      localized_sport_type: 'Multisport',
      city: '',
      state: '',
      country: 'Switzerland',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'odlo',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 328003,
      resource_state: 2,
      name: 'Grenoble Trail',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/328003/7720428/3/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/328003/7720428/3/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/328003/7720430/9/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/328003/7720430/9/small.jpg',
      activity_types: ['Run', 'VirtualRun', 'Wheelchair'],
      activity_types_icon: 'sports_run_normal',
      dimensions: [
        'distance',
        'num_activities',
        'best_activities_distance',
        'elev_gain',
        'moving_time',
        'velocity',
      ],
      sport_type: 'running',
      localized_sport_type: 'Course à pied',
      city: 'Grenoble',
      state: 'Auvergne-Rhône-Alpes',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: false,
      url: 'grenobletrail',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 803846,
      resource_state: 2,
      name: 'Run 2024 Km in 2024',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/803846/29284651/1/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/803846/29284651/1/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/803846/17962745/3/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/803846/17962745/3/small.jpg',
      activity_types: ['Run', 'VirtualRun', 'Wheelchair'],
      activity_types_icon: 'sports_run_normal',
      dimensions: [
        'distance',
        'num_activities',
        'best_activities_distance',
        'elev_gain',
        'moving_time',
        'velocity',
      ],
      sport_type: 'running',
      localized_sport_type: 'Course à pied',
      city: 'Hillsboro',
      state: 'Oregon',
      country: 'United States',
      private: false,
      member_count: 0,
      featured: false,
      verified: false,
      url: 'Run2024KMin2024',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 538072,
      resource_state: 2,
      name: 'Strava France',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/538072/12447254/2/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/538072/12447254/2/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/538072/12447246/11/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/538072/12447246/11/small.jpg',
      activity_types: [],
      activity_types_icon: 'sports_multi_normal',
      dimensions: ['moving_time', 'num_activities', 'distance', 'elev_gain'],
      sport_type: 'other',
      localized_sport_type: 'Multisport',
      city: '',
      state: '',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'stravafrance',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 158549,
      resource_state: 2,
      name: 'Salomon Running',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/158549/3390750/3/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/158549/3390750/3/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/158549/4449838/22/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/158549/4449838/22/small.jpg',
      activity_types: ['Run', 'VirtualRun', 'Wheelchair'],
      activity_types_icon: 'sports_run_normal',
      dimensions: [
        'distance',
        'num_activities',
        'best_activities_distance',
        'elev_gain',
        'moving_time',
        'velocity',
      ],
      sport_type: 'running',
      localized_sport_type: 'Course à pied',
      city: 'Annecy',
      state: 'Haute-Savoie',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'salomonrunning',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 146083,
      resource_state: 2,
      name: 'HOKA UTMB Mont-Blanc',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/146083/20888030/4/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/146083/20888030/4/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/146083/4484357/37/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/146083/4484357/37/small.jpg',
      activity_types: ['Run', 'VirtualRun', 'Wheelchair'],
      activity_types_icon: 'sports_run_normal',
      dimensions: [
        'distance',
        'num_activities',
        'best_activities_distance',
        'elev_gain',
        'moving_time',
        'velocity',
      ],
      sport_type: 'running',
      localized_sport_type: 'Course à pied',
      city: 'Chamonix-Mont-Blanc',
      state: 'Haute-Savoie',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'utmb',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 126817,
      resource_state: 2,
      name: 'Ut4M',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/126817/2441492/4/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/126817/2441492/4/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/126817/5618775/4/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/126817/5618775/4/small.jpg',
      activity_types: [],
      activity_types_icon: 'sports_multi_normal',
      dimensions: ['moving_time', 'num_activities', 'distance', 'elev_gain'],
      sport_type: 'other',
      localized_sport_type: 'Multisport',
      city: 'Grenoble',
      state: 'Isère',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'Ut4m',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 540097,
      resource_state: 2,
      name: 'Skyrunning',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/540097/12504688/4/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/540097/12504688/4/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/540097/12504704/11/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/540097/12504704/11/small.jpg',
      activity_types: ['Run', 'VirtualRun', 'Wheelchair'],
      activity_types_icon: 'sports_run_normal',
      dimensions: [
        'distance',
        'num_activities',
        'best_activities_distance',
        'elev_gain',
        'moving_time',
        'velocity',
      ],
      sport_type: 'running',
      localized_sport_type: 'Course à pied',
      city: '',
      state: '',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'skyrunning',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 1249324,
      resource_state: 2,
      name: 'Protect Our Winters France',
      profile_medium: 'avatar/club/medium.png',
      profile: 'avatar/club/large.png',
      cover_photo: null,
      cover_photo_small: null,
      activity_types: [],
      activity_types_icon: 'sports_multi_normal',
      dimensions: ['moving_time', 'num_activities', 'distance', 'elev_gain'],
      sport_type: 'other',
      localized_sport_type: 'Multisport',
      city: 'Annecy',
      state: 'Haute-Savoie',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: false,
      url: 'powfrance',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 1344034,
      resource_state: 2,
      name: 'LES GENOUX DANS LE GIF',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/1344034/34995746/1/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/1344034/34995746/1/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/1344034/34995807/2/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/1344034/34995807/2/small.jpg',
      activity_types: ['Run', 'VirtualRun', 'Wheelchair'],
      activity_types_icon: 'sports_run_normal',
      dimensions: [
        'distance',
        'num_activities',
        'best_activities_distance',
        'elev_gain',
        'moving_time',
        'velocity',
      ],
      sport_type: 'running',
      localized_sport_type: 'Course à pied',
      city: 'Annecy',
      state: 'Haute-Savoie',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'lesgenouxdanslegif',
      membership: 'member',
      admin: false,
      owner: false,
    },
  ],
  postable_clubs_count: 5,
  ftp: 0,
  bikes: [
    {
      id: 'b13116335',
      primary: false,
      name: 'triban',
      nickname: 'triban',
      resource_state: 2,
      retired: false,
      distance: 1409345,
      converted_distance: 1409.3,
    },
  ],
  shoes: [
    {
      id: 'g21184646',
      primary: false,
      name: 'NNormal Kjerag',
      nickname: null,
      resource_state: 2,
      retired: false,
      distance: 233662,
      converted_distance: 233.7,
    },
  ],
  is_winback_via_upload: false,
  is_winback_via_view: false,
};
